<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="AccountServiceTest" tests="1" skipped="0" failures="1" errors="0" timestamp="2023-04-25T04:07:21" hostname="DESKTOP-AG8QKJE" time="6.527">
  <properties/>
  <testcase name="start" classname="AccountServiceTest" time="6.527">
    <failure message="java.lang.AssertionError: Wrong answer in test #18&#10;&#10;Get /api/empl/payment should respond with status code 200, responded: 401&#10;User must login!&#10;Authentication with johndoe@acme.com / secret" type="java.lang.AssertionError">java.lang.AssertionError: Wrong answer in test #18

Get /api/empl/payment should respond with status code 200, responded: 401
User must login!
Authentication with johndoe@acme.com / secret
	at org.junit.Assert.fail(Assert.java:89)
	at org.hyperskill.hstest.stage.StageTest.start(StageTest.java:203)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass(JUnitTestClassExecutor.java:110)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:58)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:38)
	at org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass(AbstractJUnitTestClassProcessor.java:62)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
	at jdk.proxy1/jdk.proxy1.$Proxy2.processTestClass(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker$2.run(TestWorker.java:176)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.executeAndMaintainThreadName(TestWorker.java:129)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:100)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:60)
	at org.gradle.process.internal.worker.child.ActionExecutionWorker.execute(ActionExecutionWorker.java:56)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:133)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:71)
	at worker.org.gradle.process.internal.worker.GradleWorkerMain.run(GradleWorkerMain.java:69)
	at worker.org.gradle.process.internal.worker.GradleWorkerMain.main(GradleWorkerMain.java:74)
</failure>
  </testcase>
  <system-out><![CDATA[?[1;31m
Start test 1?[0m
?[0;34m
?[0m?[0;34m  .   ____          _            __ _ _
?[0m?[0;34m /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
?[0m?[0;34m( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
?[0m?[0;34m \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
?[0m?[0;34m  '  |____| .__|_| |_|_| |_\__, | / / / /
?[0m?[0;34m =========|_|==============|___/=/_/_/_/
?[0m?[0;34m :: Spring Boot ::                (v2.5.5)
?[0m?[0;34m
?[0m?[0;34m2023-04-24 23:07:22.702  INFO 13832 --- [    Test worker] account.AccountServiceApplication        : Starting AccountServiceApplication using Java 17.0.4 on DESKTOP-AG8QKJE with PID 13832 (started by ASUS in D:\workspace-eclipse\Account Service\Account Service\task)
?[0m?[0;34m2023-04-24 23:07:22.706  INFO 13832 --- [    Test worker] account.AccountServiceApplication        : No active profile set, falling back to default profiles: default
?[0m?[0;34m2023-04-24 23:07:23.650  INFO 13832 --- [    Test worker] .s.d.r.c.RepositoryConfigurationDelegate : Bootstrapping Spring Data JPA repositories in DEFAULT mode.
?[0m?[0;34m2023-04-24 23:07:23.707  INFO 13832 --- [    Test worker] .s.d.r.c.RepositoryConfigurationDelegate : Finished Spring Data repository scanning in 46 ms. Found 1 JPA repository interfaces.
?[0m?[0;34m2023-04-24 23:07:24.335  INFO 13832 --- [    Test worker] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port(s): 28852 (http)
?[0m?[0;34m2023-04-24 23:07:24.346  INFO 13832 --- [    Test worker] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
?[0m?[0;34m2023-04-24 23:07:24.347  INFO 13832 --- [    Test worker] org.apache.catalina.core.StandardEngine  : Starting Servlet engine: [Apache Tomcat/9.0.53]
?[0m?[0;34m2023-04-24 23:07:24.449  INFO 13832 --- [    Test worker] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
?[0m?[0;34m2023-04-24 23:07:24.449  INFO 13832 --- [    Test worker] w.s.c.ServletWebServerApplicationContext : Root WebApplicationContext: initialization completed in 1696 ms
?[0m?[0;34m2023-04-24 23:07:24.582  INFO 13832 --- [    Test worker] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Starting...
?[0m?[0;34m2023-04-24 23:07:24.792  INFO 13832 --- [    Test worker] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Start completed.
?[0m?[0;34m2023-04-24 23:07:24.802  INFO 13832 --- [    Test worker] o.s.b.a.h2.H2ConsoleAutoConfiguration    : H2 console available at '/h2'. Database available at 'jdbc:h2:file:../service_db'
?[0m?[0;34m2023-04-24 23:07:24.960  INFO 13832 --- [    Test worker] o.hibernate.jpa.internal.util.LogHelper  : HHH000204: Processing PersistenceUnitInfo [name: default]
?[0m?[0;34m2023-04-24 23:07:25.025  INFO 13832 --- [    Test worker] org.hibernate.Version                    : HHH000412: Hibernate ORM core version 5.4.32.Final
?[0m?[0;34m2023-04-24 23:07:25.194  INFO 13832 --- [    Test worker] o.hibernate.annotations.common.Version   : HCANN000001: Hibernate Commons Annotations {5.1.2.Final}
?[0m?[0;34m2023-04-24 23:07:25.341  INFO 13832 --- [    Test worker] org.hibernate.dialect.Dialect            : HHH000400: Using dialect: org.hibernate.dialect.H2Dialect
?[0m?[0;34m2023-04-24 23:07:26.003  INFO 13832 --- [    Test worker] o.h.e.t.j.p.i.JtaPlatformInitiator       : HHH000490: Using JtaPlatform implementation: [org.hibernate.engine.transaction.jta.platform.internal.NoJtaPlatform]
?[0m?[0;34m2023-04-24 23:07:26.010  INFO 13832 --- [    Test worker] j.LocalContainerEntityManagerFactoryBean : Initialized JPA EntityManagerFactory for persistence unit 'default'
?[0m?[0;34m2023-04-24 23:07:26.528  INFO 13832 --- [    Test worker] o.s.s.web.DefaultSecurityFilterChain     : Will secure any request with [org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter@1a34f8e2, org.springframework.security.web.context.SecurityContextPersistenceFilter@4c9bed65, org.springframework.security.web.header.HeaderWriterFilter@48d24d63, org.springframework.security.web.authentication.logout.LogoutFilter@b307030, org.springframework.security.web.authentication.www.BasicAuthenticationFilter@690e7b89, org.springframework.security.web.savedrequest.RequestCacheAwareFilter@7e35d743, org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter@28c00acd, org.springframework.security.web.authentication.AnonymousAuthenticationFilter@222a7429, org.springframework.security.web.session.SessionManagementFilter@28521ed5, org.springframework.security.web.access.ExceptionTranslationFilter@5a464be7, org.springframework.security.web.access.intercept.FilterSecurityInterceptor@6a906078]
?[0m?[0;34m2023-04-24 23:07:26.596  WARN 13832 --- [    Test worker] JpaBaseConfiguration$JpaWebConfiguration : spring.jpa.open-in-view is enabled by default. Therefore, database queries may be performed during view rendering. Explicitly configure spring.jpa.open-in-view to disable this warning
?[0m?[0;34m2023-04-24 23:07:27.138  INFO 13832 --- [    Test worker] o.s.b.a.e.web.EndpointLinksResolver      : Exposing 14 endpoint(s) beneath base path '/actuator'
?[0m?[0;34m2023-04-24 23:07:27.188  INFO 13832 --- [    Test worker] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat started on port(s): 28852 (http) with context path ''
?[0m?[0;34m2023-04-24 23:07:27.209  INFO 13832 --- [    Test worker] account.AccountServiceApplication        : Started AccountServiceApplication in 4.877 seconds (JVM running for 5.794)
?[0;34m2023-04-24 23:07:27.510  INFO 13832 --- [io-28852-exec-1] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring DispatcherServlet 'dispatcherServlet'
?[0m?[0;34m2023-04-24 23:07:27.510  INFO 13832 --- [io-28852-exec-1] o.s.web.servlet.DispatcherServlet        : Initializing Servlet 'dispatcherServlet'
?[0m?[0;34m2023-04-24 23:07:27.512  INFO 13832 --- [io-28852-exec-1] o.s.web.servlet.DispatcherServlet        : Completed initialization in 2 ms
?[0m?[1;31m
Start test 2?[0m
?[1;31m
Start test 3?[0m
?[1;31m
Start test 4?[0m
?[1;31m
Start test 5?[0m
?[1;31m
Start test 6?[0m
?[1;31m
Start test 7?[0m
?[1;31m
Start test 8?[0m
?[0;34m2023-04-24 23:07:28.196  WARN 13832 --- [o-28852-exec-10] .w.s.m.s.DefaultHandlerExceptionResolver : Resolved [org.springframework.web.bind.MethodArgumentNotValidException: Validation failed for argument [0] in public org.springframework.http.ResponseEntity<account.dto.UserDTO> account.controllers.HomeController.addNewUser(account.models.UserInfo): [Field error in object 'userInfo' on field 'name': rejected value []; codes [NotBlank.userInfo.name,NotBlank.name,NotBlank.java.lang.String,NotBlank]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [userInfo.name,name]; arguments []; default message [name]]; default message [must not be blank]] ]
?[1;31m
Start test 9?[0m
?[0m?[0;34m2023-04-24 23:07:28.226  WARN 13832 --- [io-28852-exec-1] .w.s.m.s.DefaultHandlerExceptionResolver : Resolved [org.springframework.web.bind.MethodArgumentNotValidException: Validation failed for argument [0] in public org.springframework.http.ResponseEntity<account.dto.UserDTO> account.controllers.HomeController.addNewUser(account.models.UserInfo): [Field error in object 'userInfo' on field 'name': rejected value [null]; codes [NotBlank.userInfo.name,NotBlank.name,NotBlank.java.lang.String,NotBlank]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [userInfo.name,name]; arguments []; default message [name]]; default message [must not be blank]] ]
?[1;31m
Start test 10?[0m
?[0;34m2023-04-24 23:07:28.239  WARN 13832 --- [io-28852-exec-2] .w.s.m.s.DefaultHandlerExceptionResolver : Resolved [org.springframework.web.bind.MethodArgumentNotValidException: Validation failed for argument [0] in public org.springframework.http.ResponseEntity<account.dto.UserDTO> account.controllers.HomeController.addNewUser(account.models.UserInfo): [Field error in object 'userInfo' on field 'lastname': rejected value []; codes [NotBlank.userInfo.lastname,NotBlank.lastname,NotBlank.java.lang.String,NotBlank]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [userInfo.lastname,lastname]; arguments []; default message [lastname]]; default message [must not be blank]] ]
?[1;31m
Start test 11?[0m
?[0;34m2023-04-24 23:07:28.251  WARN 13832 --- [io-28852-exec-3] .w.s.m.s.DefaultHandlerExceptionResolver : Resolved [org.springframework.web.bind.MethodArgumentNotValidException: Validation failed for argument [0] in public org.springframework.http.ResponseEntity<account.dto.UserDTO> account.controllers.HomeController.addNewUser(account.models.UserInfo): [Field error in object 'userInfo' on field 'lastname': rejected value [null]; codes [NotBlank.userInfo.lastname,NotBlank.lastname,NotBlank.java.lang.String,NotBlank]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [userInfo.lastname,lastname]; arguments []; default message [lastname]]; default message [must not be blank]] ]
?[1;31m
Start test 12?[0m
?[0;34m2023-04-24 23:07:28.263  WARN 13832 --- [io-28852-exec-4] .w.s.m.s.DefaultHandlerExceptionResolver : Resolved [org.springframework.web.bind.MethodArgumentNotValidException: Validation failed for argument [0] in public org.springframework.http.ResponseEntity<account.dto.UserDTO> account.controllers.HomeController.addNewUser(account.models.UserInfo) with 2 errors: [Field error in object 'userInfo' on field 'email': rejected value []; codes [NotBlank.userInfo.email,NotBlank.email,NotBlank.java.lang.String,NotBlank]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [userInfo.email,email]; arguments []; default message [email]]; default message [must not be blank]] [Field error in object 'userInfo' on field 'email': rejected value []; codes [Email.userInfo.email,Email.email,Email.java.lang.String,Email]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [userInfo.email,email]; arguments []; default message [email],[Ljavax.validation.constraints.Pattern$Flag;@57245532,^[a-zA-Z0-9._%+-]+@acme\.com$]; default message [must be a well-formed email address]] ]
?[1;31m
Start test 13?[0m
?[0;34m2023-04-24 23:07:28.275  WARN 13832 --- [io-28852-exec-5] .w.s.m.s.DefaultHandlerExceptionResolver : Resolved [org.springframework.web.bind.MethodArgumentNotValidException: Validation failed for argument [0] in public org.springframework.http.ResponseEntity<account.dto.UserDTO> account.controllers.HomeController.addNewUser(account.models.UserInfo): [Field error in object 'userInfo' on field 'lastname': rejected value [null]; codes [NotBlank.userInfo.lastname,NotBlank.lastname,NotBlank.java.lang.String,NotBlank]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [userInfo.lastname,lastname]; arguments []; default message [lastname]]; default message [must not be blank]] ]
?[1;31m
Start test 14?[0m
?[0;34m2023-04-24 23:07:28.288  WARN 13832 --- [io-28852-exec-6] .w.s.m.s.DefaultHandlerExceptionResolver : Resolved [org.springframework.web.bind.MethodArgumentNotValidException: Validation failed for argument [0] in public org.springframework.http.ResponseEntity<account.dto.UserDTO> account.controllers.HomeController.addNewUser(account.models.UserInfo): [Field error in object 'userInfo' on field 'password': rejected value []; codes [NotBlank.userInfo.password,NotBlank.password,NotBlank.java.lang.String,NotBlank]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [userInfo.password,password]; arguments []; default message [password]]; default message [must not be blank]] ]
?[1;31m
Start test 15?[0m
?[0;34m2023-04-24 23:07:28.301  WARN 13832 --- [io-28852-exec-7] .w.s.m.s.DefaultHandlerExceptionResolver : Resolved [org.springframework.web.bind.MethodArgumentNotValidException: Validation failed for argument [0] in public org.springframework.http.ResponseEntity<account.dto.UserDTO> account.controllers.HomeController.addNewUser(account.models.UserInfo): [Field error in object 'userInfo' on field 'password': rejected value [null]; codes [NotBlank.userInfo.password,NotBlank.password,NotBlank.java.lang.String,NotBlank]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [userInfo.password,password]; arguments []; default message [password]]; default message [must not be blank]] ]
?[1;31m
Start test 16?[0m
?[0;34m2023-04-24 23:07:28.312  WARN 13832 --- [io-28852-exec-8] .w.s.m.s.DefaultHandlerExceptionResolver : Resolved [org.springframework.web.bind.MethodArgumentNotValidException: Validation failed for argument [0] in public org.springframework.http.ResponseEntity<account.dto.UserDTO> account.controllers.HomeController.addNewUser(account.models.UserInfo): [Field error in object 'userInfo' on field 'email': rejected value [johndoeacme.com]; codes [Email.userInfo.email,Email.email,Email.java.lang.String,Email]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [userInfo.email,email]; arguments []; default message [email],[Ljavax.validation.constraints.Pattern$Flag;@57245532,^[a-zA-Z0-9._%+-]+@acme\.com$]; default message [must be a well-formed email address]] ]
?[1;31m
Start test 17?[0m
?[0;34m2023-04-24 23:07:28.323  WARN 13832 --- [io-28852-exec-9] .w.s.m.s.DefaultHandlerExceptionResolver : Resolved [org.springframework.web.bind.MethodArgumentNotValidException: Validation failed for argument [0] in public org.springframework.http.ResponseEntity<account.dto.UserDTO> account.controllers.HomeController.addNewUser(account.models.UserInfo): [Field error in object 'userInfo' on field 'email': rejected value [johndoe@google.com]; codes [Email.userInfo.email,Email.email,Email.java.lang.String,Email]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [userInfo.email,email]; arguments []; default message [email],[Ljavax.validation.constraints.Pattern$Flag;@57245532,^[a-zA-Z0-9._%+-]+@acme\.com$]; default message [must be a well-formed email address]] ]
?[1;31m
Start test 18?[0m
]]></system-out>
  <system-err><![CDATA[]]></system-err>
</testsuite>
